[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen

build_flags =
    -D USER_SETUP_LOADED=1
    -include $PROJECT_DIR/include/User_Setup.h